export enum IncidentCategory {
  LOW_TURNOUT = 'LOW_TURNOUT',
  LATE_OPENING = 'LATE_OPENING',
  EARLY_CLOSURE = 'EARLY_CLOSURE',
  MISSING_MATERIALS = 'MISSING_MATERIALS',
  VIOLENCE = 'VIOLENCE',
  INTIMIDATION = 'INTIMIDATION',
  VOTE_BUYING = 'VOTE_BUYING',
  BALLOT_SNATCHING = 'BALLOT_SNATCHING',
  UNDERAGE_VOTING = 'UNDERAGE_VOTING',
  OVER_VOTING = 'OVER_VOTING',
  DEVICE_FAILURE = 'DEVICE_FAILURE',
  SECURITY_ISSUE = 'SECURITY_ISSUE',
  RESULT_TAMPERING = 'RESULT_TAMPERING',
  OTHER = 'OTHER'
}
